### Dependencies

In [10]:
import tensorflow as tf
import numpy as np

### Utils

In [6]:
def run(operation):
    with tf.Session() as session: 
        return session.run(operation)
    
def print_run(operation):
    result = run(operation)
    print(result)

### Constants

In [7]:
description = tf.constant('Tensorflow version: ')
version = tf.constant(tf.__version__)
print_run(description + version)

m1 = tf.constant([[1, 2], 
                  [3, 4]])

m2 = tf.constant([[1], 
                  [1]])

print_run(m1 * m2)
print_run(tf.matmul(m1, m2))

print(m1.get_shape)

b'Tensorflow version: 1.12.0'
[[1 2]
 [3 4]]
[[3]
 [7]]
<bound method Tensor.get_shape of <tf.Tensor 'Const_2:0' shape=(2, 2) dtype=int32>>


### Variables

In [8]:
data = np.array([[1, 2], 
                  [3, 4]])

weights = np.array([[1], [2]])

print(data)
print('\n')
print(weights)

a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
add_operation = a + b 
multiply_operation = a * b

with tf.Session() as sess:
    add_result = sess.run(add_operation,
                          feed_dict= {a:data, b:weights})
    
    mult_result = sess.run(multiply_operation,
                           feed_dict= {a:data, b:weights})
    print('\n')
    print(add_result)
    print('\n')    
    print(mult_result)


[[1 2]
 [3 4]]


[[1]
 [2]]


[[2. 3.]
 [5. 6.]]


[[1. 2.]
 [6. 8.]]
